#define MP_FLIPPER_COMPILER
#define MP_FLIPPER_RUNTIME
#define MP_FLIPPER_MPY_SUPPORT
#define MP_FLIPPER_FIRMWARE
#define MP_FLIPPER_SPLIT_HEAP
#define MP_FLIPPER_MATH
#define MP_FLIPPER_JSON
#define MP_FLIPPER_IO

#include "mp_flipper_config.h"
